<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>_1toOneConverterOnline.Server</RootNamespace>
        <UserSecretsId>48e35aa0-959f-40c8-b65f-9c17ad7b1e9a</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.18.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Api.ProviderBuilderExtensions" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="1.18.0-rc.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12" />
        <PackageReference Include="AspNet.Security.OAuth.Discord" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\1toOneConverterOnline\1toOneConverterOnline.csproj" />
    </ItemGroup>

</Project>
