using _1toOneConverterOnline.Models;
using _1toOneConverterOnline.Models.Settings.Conversion;
using GBX.NET;
using GBX.NET.Engines.Game;
using Microsoft.Extensions.Configuration;
using System.Xml.Serialization;

namespace _1toOneConverterOnline.Tests.Other;

public class ConversionTest
{
    [Fact]
    public void Test()
    {
        var configuration = new ConfigurationBuilder()
            .AddUserSecrets<AutoGeneratedProgram>()
            .Build();

        var inputFile = configuration.GetValue<string>("ConversionTest:InputFile");

        if (string.IsNullOrEmpty(inputFile))
        {
            return;
        }

        var outputFolder = configuration.GetValue<string>("ConversionTest:OutputFolder");

        var environments = new[] { "Alpine", "Speed", "Bay" };
        var conversions = new Dictionary<string, ComplexConversion>();

        foreach (var env in environments)
        {
            using var reader = File.OpenText($"Files/{env}Conversion.xml");

            var serializer = new XmlSerializer(typeof(ComplexConversion));

            if (serializer.Deserialize(reader) is not ComplexConversion conversion)
            {
                continue;
            }

            conversions.Add(env, conversion);
        }

        var map = Gbx.ParseNode<CGameCtnChallenge>(inputFile);

        var mapModel = new Map(map);

        conversions[map.Collection.ToString()!].Convert(mapModel);

        var newFileName = Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(inputFile)) + ".Map.Gbx";
        var outputFile = string.IsNullOrWhiteSpace(outputFolder) ? newFileName : Path.Combine(outputFolder, newFileName);

        mapModel.Challenge.Save(outputFile);
    }
}
